const CVENTRIES = [
  {
    expHeading: "Coding Bootcamps EU",
    expSubheading: "2021 - Intensivschulung Frontend-Developer",
    expHardSkills: "HTML, CSS, JavaScript",
    expTooling: "VSCode, Git(-Hub), Vue, Cypress, Firebase, NPM",
    expPrinciples: "Versionierung, GitFlow, Clean Code, REST",
    expSoftSkills: "SCRUM, Teamwork, GitHub Teamprojekt",
    expProjects: "AMA-Tool, Portfolio, CBE-Tool, RandomPetFacts",
    entryHeadingOne: "Hardskills: ",
    entryHeadingTwo: "Toolings: ",
    entryHeadingThree: "Prinzipien: ",
    entryHeadingFour: "Softskills: ",
    entryHeadingFive: "Projekte: ",
    entryType: "itRelevant",
  },
  {
    expHeading: "it.schule Stuttgart",
    expSubheading: "2015-2017 - Technischer Assistent & Fachabitur",
    expHardSkills: "Java, SQL, jQuery, PHP, Python",
    expTooling: "Xampp, NetBeans, Adobe Suite, jMonkey, NodeJS",
    expPrinciples:
      "OOP, wissenschaftliches Arbeiten, ER-Diagramme, Designregeln",
    expSoftSkills: "Präsentationen, Projekte in großen Teams, Klassensprecher",
    expProjects:
      "Snake, Head-Mounted-Displays, Prozedurale Generierung, Bundeswettbewerb IT",
    entryHeadingOne: "Hardskills: ",
    entryHeadingTwo: "Toolings: ",
    entryHeadingThree: "Prinzipien: ",
    entryHeadingFour: "Softskills: ",
    entryHeadingFive: "Projekte: ",
    entryType: "itRelevant",
  },
  {
    expHeading: "SafeTec / Inflowmation",
    expSubheading: "2008-2009 - Erste Tätigkeit als Entwickler",
    expHardSkills: "HTML, CSS, vb.NET, Java",
    expTooling: "Eclipse",
    expPrinciples: "Readability, Don't repeat yourself!",
    expSoftSkills: "Sicheres Auftreten beim Kunden",
    expProjects: "Imaging for Africa, Firmenwebseite",
    entryHeadingOne: "Hardskills: ",
    entryHeadingTwo: "Toolings: ",
    entryHeadingThree: "Prinzipien: ",
    entryHeadingFour: "Softskills: ",
    entryHeadingFive: "Projekte: ",
    entryType: "itRelevant",
  },
  {
    expHeading: "Cryptocurrency",
    expSubheading: "2018-2019 - Umgang mit neuen Technologien",
    expHardSkills: "Cryptotrading, Blockchain, Mining",
    expTooling: "Wallets, Mining Rigs, Trading Plattformen",
    expPrinciples: "Marktmechanismen, Menipulation",
    expSoftSkills: "Geduld, realistische Erwartungshaltung",
    expProjects: "---",
    entryHeadingOne: "Hardskills: ",
    entryHeadingTwo: "Toolings: ",
    entryHeadingThree: "Prinzipien: ",
    entryHeadingFour: "Softskills: ",
    entryHeadingFive: "Projekte: ",
    entryType: "elseRelevant",
  },
  {
    expHeading: "Business Administration",
    expSubheading: "2013-2015 - Meinen wirtschaftliche Seite",
    expHardSkills: "Marketing, Firmengründung, BWL",
    expTooling: "ERP, Kassenbuch",
    expPrinciples: "Marketingmix, Nachhaltigkeit",
    expSoftSkills: "Zeitmanagement, Klassensprecher",
    expProjects: "`Herausbildung des Wirtschaftsliberalismus` `Nachhaltigkeit`",
    entryHeadingOne: "Hardskills: ",
    entryHeadingTwo: "Toolings: ",
    entryHeadingThree: "Prinzipien: ",
    entryHeadingFour: "Softskills: ",
    entryHeadingFive: "Projekte: ",
    entryType: "elseRelevant",
  },
  {
    expHeading: "Berufliche Tätigkeiten",
    expSubheading: "Jobs und Aushilfstätigkeiten",
    expHardSkills: "Servicemitarbeiter bei SushiCircle",
    entryHeadingOne: "2016-2017",
    expTooling: "Qualitätskontrolle bei KNV",
    entryHeadingTwo: "2012-2013",
    expPrinciples: "Verkäufer bei GameStop",
    entryHeadingThree: "2012",
    expSoftSkills: "Paketzusteller bei DPD",
    entryHeadingFour: "2010-2011",
    expProjects: "Grundwehrdienst Bundeswehr (Gebirgslogistik)",
    entryHeadingFive: "2010",
    entryType: "otherExp",
  },
  {
    expHeading: "Sonstige Tätigkeiten",
    expSubheading: "Was ich noch so getan habe",
    expHardSkills:
      "Gründung eines Vereins zur Aufklärung über Abtreibung aufgrund des §219a",
    entryHeadingOne: "2020-jetzt",
    expTooling:
      "Gründungsmitglied der Humanistischen Friedenspartei Deutschland",
    entryHeadingTwo: "2014-2016",
    expPrinciples: "Praktika: Elektriker, Zweiradmechaniker, Computerreparatur",
    entryHeadingThree: "2007",
    expSoftSkills: "Werkrealschule - Ludwig Uhland Schule Stgt.",
    entryHeadingFour: "2001-2007",
    expProjects: "Grundschule - Freie Evangelische Schule Stgt.",
    entryHeadingFive: "1996-2001",
    entryType: "otherExp",
  },
];

export default CVENTRIES;
